version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task1_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task1_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: python_app
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/task1_db
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    
    command: python -m src.main data/students.json data/rooms.json json

volumes:
  postgres_data: